server:
  port: 8222

jwt:
  secret: "Z4h5/H39t6gdMbJ0pAfce1EUn0JANtsYJWL9NLxjnGBzh0UZoh5BszZNPoKQoWS2"

spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: http://localhost:8010
            predicates:
              - Path=/api/v1/users/**
          - id: ressources
            uri: http://localhost:8060
            predicates:
              - Path=/api/v1/ressources/**
          - id: cours
            uri: http://localhost:8020
            predicates:
              - Path=/api/v1/cours/**
          - id: event
            uri: http://localhost:8030
            predicates:
              - Path=/api/v1/events/**
          - id: problem
            uri: http://localhost:8040
            predicates:
              - Path=/api/v1/problems/**
          - id: projet
            uri: http://localhost:8050
            predicates:
              - Path=/api/v1/projets/**


          - id: purchase
            uri: http://localhost:9099
            predicates:
              - Path=/api/v1/purchase/**





